language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="d61ab9a2c-fc12-4cb0-a446-d042a67f0af8"
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -savva28031997@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

